services:
  api:
    build:
      context: ./
      dockerfile: ./dockerFile
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./api:/var/www/html/api
  db:
    image: mariadb:10.9.2
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=notsafeforproduction
  search:
    image: opensearchproject/opensearch
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300' 
    environment:
      - discovery.type=single-node
    volumes:
      - ./search:/usr/share/opensearch/data
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '127.0.0.1:8181:80'
    environment:
      - MYSQL_ROOT_PASSWORD=notsafeforproduction