services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./api:/var/www/html/api
    command: sh -c "composer install && apache2-foreground"
  db:
    image: mariadb:10.9.2
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=notsafeforproduction
    command:
      --lower_case_table_names=1

    hostname: db

  search:
    build:
      context: ./search/
    ports:
      - 5050:5050
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '127.0.0.1:8181:80'
    environment:
      - MYSQL_ROOT_PASSWORD=notsafeforproduction
